name: MOFUPvP
version: ${project.version}
main: net.mofucraft.mofupvp.MOFUPvP
authors: [yossy_zip]
website: mofucraft.net

commands:
  change:
    description: マップを変更する

permissions:
  mofupvp.change:
    default: op
